### ISSUE TITLE
why is API level 21 required on Android?

### ISSUE THREAD

**Issue by ramsestom** [anoop4real/flutter_iso_countries#1]
Could you explain why there is this line in the Readme file?:  

> Android API level 21 required

Android supports Locale.getISOCountries() since API level 1 so I don't see why this lib couldn't work for android devices whith API < 21

**Comment by anoop4real** [comment]
Hi,
The method Locale.forLanguageTag is not available below API Level 21 that is why.
https://developer.android.com/reference/java/util/Locale#forLanguageTag(java.lang.String)

-anoop

**Comment by ramsestom** [comment]
I see.
Well you should just split the localIdentifier on `[_-]` separators and call `Locale(language, country))` or `Locale(language)` depending on the length of the result array (2 or 1) rather than `Locale.forLanguageTag(localeIdentifer)`. It would work just fine and remove this API 21 limitation. 
It would also remove the issue you had with casing on android as the Locale constructors normalizes the language value to lowercase and the country value to uppercase.
