### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by ramsestom** [anoop4real/flutter_iso_countries#2]
- When a country name is unknown in the requested locale, it would be better to return the default country name rather than "UnIdentified". For example, on Android if `locale.getDisplayCountry(Locale.forLanguageTag(localeIdentifer)`) return an empty string (bytheway I think there is a bug in your code as the android documentation https://developer.android.com/reference/java/util/Locale#getDisplayCountry(java.util.Locale) state that the function would return an empty string, not a null one if this country is not identified in the requested locale. So in your kotlin code you should test if null OR empty), you should default to `locale.getDisplayCountry()` and only return "UnIdentified" if this also return an empty String (which should probably never happen).

- You should add a function allowing to request a specific country given a country code and an optional locale. For example if I want to display the "ca" country to a user that has set it prefered display locale to "fr" I should be able to call the lib with something like getCountry("ca", locale: "fr") and it should return me a Country object with the "ca" code and the "Canada" name.

**Comment by anoop4real** [comment]
Hi,
Thanks for the suggestions, I will have a look.
-anoop

**Comment by anoop4real** [comment]
Added API for getting a specific country in  v1.1.1
