### ISSUE TITLE
- `iso_countries` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### ISSUE THREAD

**Issue by nxg916** [anoop4real/flutter_iso_countries#3]
- `iso_countries` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

when run ios

**Comment by anoop4real** [comment]
Is it a warning or does it prevent from running?

**Comment by anoop4real** [comment]
It seems to be an issue with Swift plugins, can you try the below steps while I look for a  fix
[https://github.com/flutter/flutter/issues/25676](url)
`
    A Bridging Header must be created.
    Open the project with XCode. Then choose File -> New -> File -> Swift File.
    A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.). XCode will ask you if you wish to create Bridging Header, click yes.
    Make sure you have use_frameworks! in the Runner block, in ios/Podfile。
    Make sure you have SWIFT_VERSION 4.0 selected in you XCode -> Build Settings
    Do flutter clean
    Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update
`

**Comment by anoop4real** [comment]
Closing as there is no further response
