### ISSUE TITLE
The plugin `iso_countries` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by loki187** [anoop4real/flutter_iso_countries#8]
After updating to Flutter 2.5 I got following message:
The plugin `iso_countries` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs. If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by anoop4real** [comment]
I will check that out

**Comment by panchalAlpit** [comment]
I'm fixing the same issue.

**Comment by anoop4real** [comment]
@loki187 @panchalAlpit  A new version has been uploaded 2.1.0 addressing the issue. Please check and let me know if it works.

**Comment by panchalAlpit** [comment]
@anoop4real Thank you so much for fixing this issue, now it completely works in android. 
Thanks again.

**Comment by loki187** [comment]
@anoop4real Thanks for fix. It also works on iOS. Can be closed.

**Comment by anoop4real** [comment]
Thanks closing it
